### ISSUE TITLE
Fatal error when alterGenderID fn cannot accept comma separated integer argument 

### ISSUE THREAD

**Issue by monishdeb** [eileenmcnaughton/nz.co.fuzion.extendedreport#587]
Backtrace : 
```
        [03-Dec-2024 00:44:41 America/Montreal] PHP Fatal error:  Uncaught TypeError: CRM_Extendedreport_Form_Report_ExtendedReport::alterGenderID(): Argument #1 ($value) must be of type ?int, string given, called in /var/www/example.com/htdocs/wp-content/plugins/civicrm/civicrm/CRM/Report/Form.php on line 2579 and defined in /var/www/example.com/htdocs/wp-content/uploads/civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php:6406
        Stack trace:
        #0 /var/www/example.com/htdocs/wp-content/plugins/civicrm/civicrm/CRM/Report/Form.php(2579): CRM_Extendedreport_Form_Report_ExtendedReport->alterGenderID()
        #1 /var/www/example.com/htdocs/wp-content/uploads/civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php(2362): CRM_Report_Form->formatDisplay()
        #2 /var/www/example.com/htdocs/wp-content/uploads/civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php(1652): CRM_Extendedreport_Form_Report_ExtendedReport->formatDisplay()
        #3 /var/www/example.com/htdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(646): CRM_Extendedreport_Form_Report_ExtendedReport->postProcess()
        #4 /var/www/example.com/htdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Submit.php(56): CRM_Core_Form->mainProcess()
        #5 /var/www/example.com/htdocs/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Submit->perform()
        #6 /var/www/example.com/htdocs/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle()
        #7 /var/www/example.com/htdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php(356): HTML_QuickForm_Page->handle()
        #8 /var/www/example.com/htdocs/wp-content/plugins/civicrm/civicrm/CRM/Utils/Wrapper.php(98): CRM_Core_Controller->run()
        #9 /var/www/example.com/htdocs/wp-content/plugins/civicrm/civicrm/CRM/Report/Page/Instance.php(75): CRM_Utils_Wrapper->run()
        #10 /var/www/example.com/htdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(338): CRM_Report_Page_Instance->run()
        #11 /var/www/example.com/htdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(74): CRM_Core_Invoke::runItem()
        #12 /var/www/example.com/htdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke()
        #13 /var/www/example.com/htdocs/wp-content/plugins/civicrm/civicrm.php(1231): CRM_Core_Invoke::invoke()
        #14 /var/www/example.com/htdocs/wp-includes/class-wp-hook.php(324): CiviCRM_For_WordPress->invoke()
        #15 /var/www/example.com/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
        #16 /var/www/example.com/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
        #17 /var/www/example.com/htdocs/wp-admin/admin.php(259): do_action()
 ```

**Comment by monishdeb** [comment]
I will submit a PR shortly.
