### ISSUE TITLE
Participant reports contain a broken table reference

### ISSUE THREAD

**Issue by verblet** [eileenmcnaughton/nz.co.fuzion.extendedreport#63]
CiviCRM: 4.6.14
Drupal: 7.44

When saving a new 'Extended Report - Participant Line Items' report, I get a DB error (pasted below).

Taking a quick look this appears to be related to the changes in the participant JOIN from this pull request: https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/58 @PalanteJon 

The join references a $_participantTable value that is not available.

```
[info] $backTrace = #0 /srv/XXXXXX/public/sites/all/modules/civicrm/CRM/Core/Error.php(235): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 [internal function](): CRM_Core_Error::handle(Object(DB_Error))
#2 /srv/XXXXXX/public/sites/all/modules/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error))
#3 /srv/XXXXXX/public/sites/all/modules/civicrm/packages/DB.php(976): PEAR_Error->PEAR_Error("DB Error: no such table", -18, 16, (Array:2), "SELECT SQL_CALC_FOUND_ROWS civicrm_contact.display_name as civicrm_contact_ci...")
#4 /srv/XXXXXX/public/sites/all/modules/civicrm/packages/PEAR.php(564): DB_Error->DB_Error(-18, 16, (Array:2), "SELECT SQL_CALC_FOUND_ROWS civicrm_contact.display_name as civicrm_contact_ci...")
#5 /srv/XXXXXX/public/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -18, NULL, NULL, "SELECT SQL_CALC_FOUND_ROWS civicrm_contact.display_name as civicrm_contact_ci...", "DB_Error", TRUE)
#6 /srv/XXXXXX/public/sites/all/modules/civicrm/packages/DB/mysql.php(895): DB_common->raiseError(-18, NULL, NULL, NULL, "1146 ** Table 'civicrm.cp' doesn't exist")
#7 /srv/XXXXXX/public/sites/all/modules/civicrm/packages/DB/mysql.php(328): DB_mysql->mysqlRaiseError()
#8 /srv/XXXXXX/public/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysql->simpleQuery("SELECT SQL_CALC_FOUND_ROWS civicrm_contact.display_name as civicrm_contact_ci...")
#9 /srv/XXXXXX/public/sites/all/modules/civicrm/packages/DB/DataObject.php(2442): DB_common->query("SELECT SQL_CALC_FOUND_ROWS civicrm_contact.display_name as civicrm_contact_ci...")
#10 /srv/XXXXXX/public/sites/all/modules/civicrm/packages/DB/DataObject.php(1634): DB_DataObject->_query("SELECT SQL_CALC_FOUND_ROWS civicrm_contact.display_name as civicrm_contact_ci...")
#11 /srv/XXXXXX/public/sites/all/modules/civicrm/CRM/Core/DAO.php(321): DB_DataObject->query("SELECT SQL_CALC_FOUND_ROWS civicrm_contact.display_name as civicrm_contact_ci...")
#12 /srv/XXXXXX/public/sites/all/modules/civicrm/CRM/Core/DAO.php(1180): CRM_Core_DAO->query("SELECT SQL_CALC_FOUND_ROWS civicrm_contact.display_name as civicrm_contact_ci...", TRUE)
#13 /srv/XXXXXX/public/sites/all/modules/civicrm/CRM/Report/Form.php(2803): CRM_Core_DAO::executeQuery("SELECT SQL_CALC_FOUND_ROWS civicrm_contact.display_name as civicrm_contact_ci...")
#14 /srv/XXXXXX/public/sites/all/modules/civicrm/extensions/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php(1801): CRM_Report_Form->buildRows("SELECT SQL_CALC_FOUND_ROWS civicrm_contact.display_name as civicrm_contact_ci...", (Array:0))
#15 /srv/XXXXXX/public/sites/all/modules/civicrm/CRM/Core/Form.php(345): CRM_Extendedreport_Form_Report_ExtendedReport->postProcess()
#16 /srv/XXXXXX/public/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Submit.php(74): CRM_Core_Form->mainProcess()
#17 /srv/XXXXXX/public/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Submit->perform(Object(CRM_Extendedreport_Form_Report_Price_Lineitemparticipant), "submit")
#18 /srv/XXXXXX/public/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Extendedreport_Form_Report_Price_Lineitemparticipant), "submit")
#19 /srv/XXXXXX/public/sites/all/modules/civicrm/CRM/Core/Controller.php(353): HTML_QuickForm_Page->handle("submit")
#20 /srv/XXXXXX/public/sites/all/modules/civicrm/CRM/Utils/Wrapper.php(115): CRM_Core_Controller->run()
#21 /srv/XXXXXX/public/sites/all/modules/civicrm/CRM/Report/Page/Report.php(76): CRM_Utils_Wrapper->run("CRM_Extendedreport_Form_Report_Price_Lineitemparticipant", NULL, NULL)
#22 /srv/XXXXXX/public/sites/all/modules/civicrm/CRM/Core/Invoke.php(312): CRM_Report_Page_Report->run((Array:4), NULL)
#23 /srv/XXXXXX/public/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:14))
#24 /srv/XXXXXX/public/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:4))
#25 /srv/XXXXXX/public/sites/all/modules/civicrm/drupal/civicrm.module(489): CRM_Core_Invoke::invoke((Array:4))
#26 [internal function](): civicrm_invoke("report", "price", "lineitemparticipant")
#27 /srv/XXXXXX/public/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:3))
#28 /srv/XXXXXX/public/index.php(21): menu_execute_active_handler()
#29 {main}
```

**Comment by PalanteJon** [comment]
Hmm - I thought I'd found only two reports that referenced this function.  I'll patch this today.

**Comment by PalanteJon** [comment]
Oh hell, when I searched for reports that used that callback, I only searched the "Event" folder.  Doing a more appropriate grep, I can at least see that this is the only report I broke.
@verblet - I looked over the logic of the change, and I don't see any reason why inserting the same line that I inserted in the other reports: 
```php
protected $_participantTable = 'civicrm_participant';
```
wouldn't solve the problem here as well.  And in fact I just inserted that line into a local copy, and I stopped getting the error you described.  However, I don't have any sites that would produce a meaningful report from that data, so I'm a bit hesitant to call that a complete fix without a test.  Could you please try inserting that line into `nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/Price/Lineitemparticipant.php` and let me know if it works?  You can insert it anywhere between the declaration of the class (line 5) and the first function (line 18).

Since this is 99% likely to be the solution, I'll get a PR prepped right away.  Sorry for my insufficient grepping to both you and Eileen!

**Comment by verblet** [comment]
I've tested this myself and it works, thank you.
